Amsterdam/mapserver

- kbk10_zw.xml
- kbk50_zw.xml
- topografie.map
kbka50 zwartwit en kbk10 (nog niet volledig)
> opzet zw kaart

- kbk10_zw.xml
- kbk50_zw.xml
deze kbk10 is aangepast aan de kleuren van kbka50 van donderdag jl
> update colors oa. lb en wegen

- kbk10_zw.xml
- kbk50_zw.xml
- topografie.map
aanpassingen nav commentaar van Rob
> update wegen zwartwit

- README.md
- docker-compose.yml
- docker/docker-entrypoint.sh
- monumenten.map
map server:
monument coordinaten - point
monument geometrie - polygon
> Feature 739/monumenten

- header.inc
- private/header.inc
- topografie.map
Fixt probleem met QGIS overgang KBKA10 naar BGT.
> Show map at and around minscaledenom/maxscaledenom.

- bgt.map
- bgt_light.xml
- bgt_zw.xml
- kbk10.map
- kbk10_light.xml
- kbk10_zw.xml
- kbk50.map
- kbk50_light.xml
- kbk50_zw.xml
- planologischezonesschiphol.map
- topografie.map
- Added background color and transparent = false to topografie.map
- all color hex to capital letters
- a lot of updates in the visualization of bgt.
> background color, transparent false, captial letters, update vis

- afval.map
plastic containers afval afstanden ontbraken nog.
> add plastic fraction to afvalcontainers

- bgt.map
users where missing the noord-zuidlijn in the map visualisation
> placed metro above all other objects

- bgt.map
- lufo.map
- lufo2018.map
Added new aerial photograph of 2018.
> Aerial photograph 2018

- private/erfpacht.map
Misschien nog wat kleurtjes aanpassen?
> DP-5923 - Erfpacht kaartlaag

- overlastgebieden.map
added vuurwerkvrijezone and vuurwerkvrijezone_label
> added vuurwerkvrijezone

- panorama.map
A small addition that prevents unblurred panoramas to cancel out blurred ones.
> Add status done to inner query

- afval.map
tada! live enevo vulgraden in database.
> add live fill level enevo

- gebieden.map
grootstedelijk_regio_amsterdam
grootstedelijk_regio_omgevingsdienst
They are both part of the group grootstedelijkgebieden
> DP-6383 - Add new layers for grootstedelijke gebieden :

- vezips.map
> Tweak vezip legend

- docker/000-default.conf
- docker/docker-entrypoint.sh
Wijzig locatie van config file Dan is het in iede geval direct te testem .
> Serve config.json from sld. Then no Openstack changes are required

- docker-compose-private.yml
- docker-compose.yml
- vastgoed.map
- Made a subquery in vastgoed datasource - otherwise it doesn't work
- Added LEGEND_URL to docker-compose - otherwise it doesn't work locally
> Small fixes in datasource vastgoed and docker-compose

- milieuzones.map
> Remove Milieuzones Touringcar 2020

- bag.map
DS-128 - Make legend for Pand, Ligplaats, Standplaats and verblijfsobj…ect by adding NAME elements to CLASS blocks
> DS-128 Better legends 

- bgt.map
- sld/bgt_light.xml
- sld/bgt_zw.xml
The associated materialized view has been removed.
> Removed terreindeel_vlak4 from bgt map.

- Jenkinsfile
Basis has removed this env var.
> Remove use of JENKINS_HTTP_PROXY_STRING

- panorama.map
https://datapunt.atlassian.net/browse/DI-299
> Add 2020 as panorama class

- fietspaaltjes.map
Verbeterde versie, met WFS en de copy/paste error is gefixed.
> Fietspaaltjes

- hoofdroutes.map
As requested in https://datapunt.atlassian.net/browse/DI-403
> Hoofroutes colors

- hoofdroutes.map
> Fix spelling mistake

- parkeervakken.map
> [DS-255] field change in DB geom to geometry

- energie.map
Resolves: [DS-353]
[DS-353]: https://datapunt.atlassian.net/browse/DS-353
> [DS-353] Added bouwstroompunten to energie

- private/header.inc
EPSG:4258 projection was missing in private/header.inc
> [SYNC] synced srs projections private/header.inc

- woningbouw.map
Based on specifications: https://wiki.data.amsterdam.nl/doku.php?id=start:toepassingen:datasquad_ruimte:plaatsing_afvalcontainers:ontwerp#detail_pagina_gebied_bouwblok_woningen
> [DS-516] added map woningbouw

- gebieden.map
> Change labels and switch colors

- docker/docker-entrypoint.sh
This reverts commit 7f5e5b90b02f597a8b55c922439a03dd8f2f615b.
Seems to make the issue worse.
> Revert "Remove stale socket files on start"

- energie.map
- Changed the values conditions per category so there is no overlap between each category
> [Bouwstroompunt] changed category value ranges

- private/brandkranen.map
> Kaartlaag brandkranen

- parkeervakken.map
- Changed colorways for laden&lossen for parkeervakkenreservering
> parkeervakken: Laden&Lossen reservering changed colorways

- docker-compose.yml
- ondergrond.map
- tools/make_mapfile_config.py
for Datateam Stedelijke ontwikkeling. Optional zoom denominator bounds and other extras will be added after their business analyst has reviewed on ACC.
> Maplayers for ondergrondse objecten, leidingen and eisvoorzorgsmaatregelen

- ondergrond.map
> Connection pooling and predefined extent bbox for ondergrond layers

- ondergrond.map
Parametrised with stelsel_type and corrected CRS.
> Add rioolleidingen maplayer

- ondergrond.map
- ondergrond/eisvoorzorgsmaatregelen_layer.inc
- ondergrond/kabels_en_leidingen_layer.inc
- ondergrond/objecten_layer.inc
- ondergrond/rioolleidingen_layer.inc
* Make each class in rioolleidingen a layer
* Parametrize kabels en leidingen so that filtering doesnt occur serverside (each layer is otherwise issuing a query for the full data)
* Make ondergrond Kadaster maps use the new tables
> Split waternet rioolleidingen layers

- energie.map
Updated the filtering on column capaciteit for bouwstroompunten table due to data changes
> bouwstroompunten: filtering on column capaciteit

- docker-compose.yml
- entry_form.md
- ondergrond.map
- ondergrond/eisvoorzorgsmaatregelen_layer.inc
- ondergrond/kabels_en_leidingen_layer.inc
- ondergrond/objecten_layer.inc
- ondergrond/rioolleidingen_layer.inc
Also contains the draft map reqest form
> Explicitly query only relevant data in klic layers

- gebieden.map
changed the grootstedelijke gebieden filters due to new resource data
> Grootstedelijke gebieden: new filters

- reclame.map
- changed the connection for reclame data to referentie database (was referencing a legacy database).
- cleaned up some filtering
> reclame: connection to ref.db

- README.md
Works around VPN issues. To be rewritten as a script later; something that works is better than something that doesn't.
> Replace update_db.sh instructions

- gen_ziektenplagenexotengroen.py
- private/ziektenplagenexotengroen.map
Also, generate this file. It's too repetitive to type and mapfile syntax isn't powerful enough (AFAICT) to parametrize an included file.
For [AB#77375](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/77375). Closes #352.
> Turn ziektenplagenexotengroen classes into layers

- .gitignore
- beschermdestadsdorpsgezichten.map
- gen_beschermdestadsdorpsgezichten.py
- gen_ziektenplagenexotengroen.py
- generate.py
- private/ziektenplagenexotengroen.map
Fixes [AB#78239](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/78239).
> Add beschermdestadsdorpsgezichten

- adresseerbare_objecten/ligplaatsen.inc
- adresseerbare_objecten/standplaatsen.inc
- adresseerbare_objecten/verblijfsobjecten.inc
Missed in 57c976a68e20852bf136d6b5e2c4ff73b0faa027. Broke some maps.
> s|connection_|connection/|g in included files

- tools/make_indexjson.py
For [AB#80357](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/80357).
> make_indexjson: Handle files that mappyfile doesn't get

- aardgasvrij.map
> Port aardgasvrij to refdb

- planologischegeluidszones.map
> Port planologischegeluidszones to refdb

- externeveiligheid.map
- planologischezonesschiphol.map
- vastgoed.map
> Port externeveiligheid, planologischezonesschiphol, vastgoed to refdb

- gen_overlastgebieden.py
- gen_ziektenplagenexotengroen.py
- overlastgebieden.map
Generate overlastgebieden.map while here. Also fixes some copy-paste errors and missing labels in that map.
> Add layer blowverbodsgebied

- bomen.map
- gen_bomen.py
Also changes the title at the request of the data owners.
> Rename vegetatieobjecten_bomen -> bomen

- .github/workflows/check_generated.yml
- Dockerfile
- Dockerfile_noproxy
- Dockerfile_noproxy_private
- Dockerfile_noproxy_tiles
- Dockerfile_private
- Dockerfile_tiles
- tools/make_indexjson.py
It's slow and doesn't parse all of our maps anyway.
Generated index.json file is unchanged.
> Generate index.json without mappyfile

- bomen.map
- gen_bomen.py
Full name is already the wms_title.
> Use [a-z] for layer names in bomen

- tools/make_indexjson.py
Didn't handle single quotes gracefully and ran into some encoding issue on ACC.
> Make make_indexjson more robust

- brk.map
- brk2.map
No two types of objects should display at any single scale.
> Fix BRK2 scales

- Dockerfile
- Dockerfile_noproxy
- Dockerfile_noproxy_private
- Dockerfile_noproxy_tiles
- Dockerfile_private
- Dockerfile_tiles
- bomen.map
- gen_bomen.py
- tools/99timeout
> Don't filter trees on typeEigenaarPlus

- brk2.map
Following discussion with @DonQueso89.
> Disable WFS for BRK2

- tools/auth_check.py
- tools/requirements.txt
- tools/utils.py
This is exactly the auth checker as it occurs on the `az` branch. I need the improvements now. The `az` branch should rebase cleanly on top of master with this branch merged.
Updates AB#93130.
> Improved auth checker

- woningbouw.map
Now uses BAG directly, instead of the copy that got removed.
> Reintroduce part of woningbouw mapfile

- hoofdroutes.map
-1 orphan mapfile. Ref AB#98099.
> Team mobiliteit just claimed hoofdroutes.map

- jwtproxy/src/server.py
Because the loggers are defined at module level,
the config needed by the loggers also needs to be
available at this level.
> Move logging setup to the module of jwtproxy.server

- private/handelsregister.map
Change tabs to spaces to make future diffs easier to follow.
> Reindent private/handelsregister

- meldingen_huidige_jaar.map
- meldingen_indicatoren.map
- meldingen_vorige_jaar.map
Database aanpassingen voor werking met acc refdb en kleine visualisatie veranderingen.
> Database aanpassingen

- meldingen_huidige_jaar.map
- meldingen_vorige_jaar.map
Tabel verwijzing op verzoek gewijzigd
> Connectie updates

- meldingen_huidige_jaar.map
- meldingen_indicatoren.map
- meldingen_vorige_jaar.map
Label toegevoegd, abstract aangepast.
> Label toegevoegd, abstract aangepast.

- .github/workflows/trigger-ado-deploy.yml
When something changes, it need to be tested first on the dev environment, before it gets deployed to prd.
> Better to deploy to dev env. first on merge to main

- touringcars.map
Ik vergat dit toe te voegen, excuus.
> vergeten deel

- Dockerfile
upgrade ubuntu from 18.04 to 22.04.
> 22.4 dockerfile build

- biz.map
This reverts part of commit f3e077b6879abedc084d47a37688169a7594573e. Ownership of data is unclear.
> Revert "Port BIZ to refdb"

- energie.map
Zie commit message voor details.
Closes #476.
> Bug fixes for energie.map

- biz.map
This reverts commit 890608385dd1b9521a846de32838758e0d005984. Issue with data ownership will be resolved later.
> Port BIZ to refdb, second try

- parkeerzones.map
- parkeerzones_uitz.map
Switch naar refdb en nodige aanpassingen.
> Refdb aanpassingen voor parkeerzones mapfiles

- nap.map
Omzetten naar refdb en aanpassingen aan kolomnamen.
> Aanpassen bron naar refdb

- vezips.map
Tabel naam aangepast, geen andere dingen veranderd.
> Omzetten naar refdb vezips

- jwtproxy/src/server.py
token
Because we are now exposing the JWT proxy externally, requests without a JWT token are now passed on to the public mapserver instance.
However, this instance is missing the private maps, which would lead to a 404. We want to generate a 403 for the private maps, so a check is added for the incoming path and a 403 is added if needed.
One map (ondergrond) has a public and a private version (private has more layers). We do not generate a 403 for this map. However, the mapserver itself gives a sensible response about the layer not being available.
> AB#10367 Generate 403 Forbidden response for private maps if no JWT

- gen_ziektenplagenexotengroen.py
- ziektenplagenexotengroen.map
> Restrict ziektenplagenexotengroen to current year

- gen_ziektenplagenexotengroen.py
- ziektenplagenexotengroen.map
This reverts commit 8383d78f628b44fc6ff71db1d1bb5601f50b056d. Change should have gone live just yet. Needs more testing and fixing.
> Revert "Restrict ziektenplagenexotengroen to current year"

- .github/workflows/check_generated.yml
- docker-compose.yml
- docker/docker-entrypoint.sh
PR #525 removed the last use of this connection, so same recipe as #521.
> Remove remnants of NAP database connection

- Dockerfile
- docker/docker-entrypoint.sh
referentie kaarten zijn verplaatst. Check of de bestanden bestaan voordat ze worden aangeroepen
> Fix startup problems with topo

- VIS.map
Update visualisation according to specs from business.
> Cartographic updates Verkeersinformatiesystemen

- gen_ziektenplagenexotengroen.py
- ziektenplagenexotengroen.map
Fixes bug in production for ERP "Gemeld" class. Also more easy to track names for the layers.
> Unique layers in erp/jdk MAP file.

- verkeersinformatiesystemen.map
Also some indentation improvements.
> Decrease buffer to allow more labels to be positioned.

- eigendommen.map
- erfpacht.map
Changed calls to old dataselectie database to use the new dataselectie_legacy schema in dataservices.
> AB#110661 use dataselectie schema

- nieuwbouwplannen.map
Following conventions we discussed last week.
> Adjust metadata and add legend titles.

- nieuwbouwplannen.map
> Add 'fase' to legend text.

- .maptile_template.txt
Latest changes in nieuwbouwplannen have been added to the template to be used for reference and future MAP files.
> Describe additional meta tags for WFS and WMS GetFeature(-Info)

- nieuwbouwplannen.map
> Layer and class names lower case without special characters.

- .github/workflows/trigger-ado-deploy.yml
> remove msagent option from pipeline trigger

- bgtobjecten.map
These are the main layers requested by iAsset.
> Update queries for 'afvalbak', 'afval apart plaats', and 'boom'.

- .gitignore
- docker/docker-entrypoint.sh
Before creating the connection files, the connection directory is created first.
> Errors when connection directory does not exist

- .github/workflows/trigger-ado-deploy.yml
Updated a changed parameter in the pipeline yaml. The old value no longer exists, meaning the trigger would never be able to work.
> updated job template parameter to reflect the correct options

- Dockerfile.database
> Bump postgis to 14.3.5

- .github/workflows/test.yml
- Dockerfile
- Dockerfile.private
- Dockerfile.topografie
- compose.yml
- docker/docker-entrypoint.sh
* Make the compose file work again
* speed up image build
* Fix bounding box test
> Quality of life fixes
