header.inc, private/header.inc
MapProxy adheres to OGC spec: 1px ~ 0.28 mm. Thus, 25.4/0.28 ~= 91dpi.
=> Fix for MapProxy zoom calculations.

bgt.map, kbk10.map, kbk10_light.xml, kbk10_zw.xml, kbk50.map
- Gebouwen donkerder, voetpaden lichter.
- Transitie wit. 
- Parkeer vlakken bij wegdeel getrokken. 
- sporen op hoogte niveau behalve ondergronds.  (nog niet in de xml)
=> update zoom level kbk10, colors in BGT, 10 and 50

bgt.map, kbk10.map, kbk50.map, sld/kbk10_light.xml, sld/kbk10_zw.xml, sld/kbk50_light.xml, sld/kbk50_zw.xml, topografie.map, topografie_wm.map
Bij de webmercator tiling schema op zoom level 15 was de kbk50 te grof. Door de schaal naar 20.000 te zetten wordt de kbk10 getoond op zoom level 15. Bij de RD tiling schema verandert er niks. 
Hopelijk is dit niet een te grote aanslag op de tijd die het kost om de tegels te renderen?  
Daarnaast ook een kleur voorstel gedaan voor een andere kleur voor de BAG lig en staan plaatsen.
=> kbk50 naar schaal 20.000 ipv 12.500 

panorama.map
The year was deduced from timestamp, which was not always the same as the
meta-data for year
=> Changed source of year to calculated year

panorama.map
Panoramas have a status, but only those that are normalized and blurred
are to be shown on the site. This works for API, but not yet for maps,
therefore behaviour on the site was not consistent between API and maps.
This fixes that.
=> Show only panoramas that are 'done'

panorama.map
As it turns out the maplayer panorama_new doesn't play nice with WFS.
That needs to be addressed. In the meantime recent panoramas are
accesable in the old layer. Because the geo-view has been removed, the
query from that view has been pasted into the data-source. Styling of
dots has been copied from panorama_new layer.
=> Restore maplayer for panorama_recent WFS

evenementen.map
After changes in the import process the database-schema of evenementen
is slightly changed (other srid, some other fieldnames), this propagates
these changes.
=> Changed evenementen map to reflect database changes

evenementen.map
Geosearch expects the geometry column to be RD. Therefore the
srid of the geometry field of evenementen (and the default projection
at import) is changed.
This change follows the underlying data change
=> Changed the projection of evenementen to follow DB change

bekendmakingen.map
The `cirkel_lichtrood` symbol is nog available, so whe choose an
existing one. Ideally new icons should be added, because this maps
exhausts the available list.
=> Choose existing symbol for kapvergunning

bekendmakingen.map
because of changed order of layers
=> changed inspraak icon

docker/mpm_event.conf
Tiling fails with message  `server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting`, MaxRequestWorkers bears relation to ServerLimit x ThreadsPerChild
=> Update mpm_event config

planologischezonesschiphol.map
ows:title bijgewerkt zodat in QGIS dezelfde omschrijving wordt getoond als in het Data Portaal
=> WFS laag naam in sync gebracht met Data Portaal

huishoudelijkafval.map
The feature_id for container was referring to a wrong field
leading to problem in WFS generation (entity ref issues
because of char '&' in the field that was used.
=> Fix gml_featureid for container.

bag.map
This reverts parts of f3ed9993b91ea55aae48cf5a2c9676d26ac4f44c.
Blijkt dat de lagen altijd samengevoegd werden omdat de GROUP dezelfde identifier gebruikte als de globale NAME van de map. Daardoor werden ook de lagen met een andere GROUP toch samengevoegd in de globale “bag” groep
=> Fix BAG ungrouping, while keeping compatibility

bag.map
Setting a layer type overrides GeoJSON output making MultiPolygon be served as Polygons.
See discussion in https://lists.osgeo.org/pipermail/mapserver-users/2018-January/080439.html
Setting type to Geometry in metadata as suggested there to override this behaviour.
=> Added geometry type to enable MultiPolygon's in GeoJSON

bag.map
Schijnbaar kunnen niet alle clients om met een spatie in de WFS laag naam. Bij deze haal ik hem er dus uit.
=> Spatie uit WFS layer naam gehaald

parkeervakken.map
To select a specific tijdvak (there are four defined), the parameter tijdvak was added. It can be used in the URL like so: http://localhost:8383/maps/parkeervakken?tijdvak=00:00:00_06:59:00,07:00:00_17:00:00&version=1.3.0&service=WMS
The regime ('parkeervakken_tijdvakken_kiss_ride','parkeervakken_tijdvakken_laden_lossen',parkeervakken_tijdvakken_taxistandplaats') can be specified in the build in parameter layers.
It also possible to use call the WFS like this to get data for a specific tijdvak for a specific regime:
http://localhost:8383/cgi-bin/mapserv?map=/srv/mapserver/parkeervakken.map&service=WFS&version=1.1.0&request=GetFeature&typename=parkeervakken_tijdvakken_laden_lossen&featureID=parkeervakken_tijdvakken_laden_lossen.00:00:00_23:59:00&propertyName=tijdvak,begin_tijd,eind_tijd …
=> [DS-255] Added an attribute to use as parameter in URL

precariobelastingen.map
**Contains 4 categories:**
1. - Bedrijfsvaartuigen  -- tariefgebied_A en B
2. - Passagiersvaartuigen  -- tariefgebied_A en B
3. - Woonschepen  -- tariefgebied_A, B en C
4. - Terrassen  -- tariefgebied_A, B en C
Colors tariefgebieden conform specs.
**URL param filter option:** tariefgebied
**URL param filter option values:** A, B or C
**Example:**
_var wmsLayer = L.tileLayer.wms('http://localhost:8383/maps/precariobelastingen?tariefgebied=B&version=1.3.0&service=WMS', {
layers: ['precariobelastinggebieden_passagiersvaartuigen', 'precariobelastinggebieden_terrassen'],
transparent: true,
format: 'image/png',
isBaseLayer : false,
tiled: true,
maxBounds: BOUNDS,
crs: L.CRS.RD
} ).addTo(mymap);_
Resolves: [DS-288]
=> [DS-288] Added the precariobelastingen layer

precariobelastingen.map
New specifications, the determination of a precariobelastinggebied is based on the rate(tarief). Not on the geometry itself.
Resolves: [DS-288]
[DS-288]: https://datapunt.atlassian.net/browse/DS-288
=> [DS-288] Modified the identification of precariobelastinggebieden

precariobelastingen.map, touringcars.map
Due to new specs the titel field is replaced by omschrijving.
Also removed an unnecessary END tag in the precariobelastingen.
Resolves: [DS-352]
[DS-352]: https://datapunt.atlassian.net/browse/DS-352
=> [DS-352] Replaced titel by omschrijving in Touringcars

docker/docker-entrypoint.sh
This is a attempt to fix reboot container problems. Perhaps the  image is
kept after a container reboot, and the existing pid file gives problems when starting
apache. This is copied from the official apache httpd docker repository
https://github.com/docker-library/httpd/blob/master/2.4/httpd-foreground
=> Remove old pid file before starting  apache server.

afval.map
The connections and logica for "containers" and "wegingen" has been adjusted to the new tables in de dataservices MD. Except for sensordata (sidcon, enevo). These must be unchanged.
=> [DS-486] changed container part of afval.map (part2)

docker/000-default.conf
This will be added by HAProxy and then contain only the origin
=> Remove Access-Control-Allow-Origin header in Apache

Dockerfile, Dockerfile_noproxy, Dockerfile_noproxy_private, Dockerfile_noproxy_tiles, Dockerfile_private, Dockerfile_tiles
They pulled in compilers and libraries for building GDAL and Mapserver, but haven't built those since 2019.
=> Clean Dockerfiles

energie.map
Recently the bouwstroompunten is differentiated to bouwstroompunten for Markt, Evenement or general bouwstroompunt. There is also a sub division for categories of electric capacity. On data.amsterdam.nl the data on the map must be selectable. There will be the 3 base layers and within 4 sublayers. Like so:
Main:
- Markt
- Evenement
- Bouwstroompunt
Sub:
- tot 3 x 25 A
- 3 x 25 A tot 3 x 40 A
- 3 x 40 A tot 3 x 63 A
- groter of gelijk aan 3 x 80 A
Because they each combination (main x sub) must be selectable (turn off/on), the combinations have there own layer in the WMS.
There is also an 'unkown' category added for data records without a capacity value.
=> Bouwstroompunt layers to energie WMS

afval.map
On request of datateam beeldschoon, changed the color definition of the category 350-370 M for loopafstanden container Textiel
=> changed color for categorie 350 - 370 M

beheerkaart.map
Beheerkaart toegevoegd.
De beheerkaart toont de publieke ruimte uitgesplitst
naar zakelijk recht. Het laat zien welk zakelijk recht
de Gemeente Amsterdam heeft op een kadastraal object en of
dit recht belast is met opstal en/of erfpacht.
Zodat duidelijk is voor welk deel van de publieke ruimte
de Gemeente beheersverantwoordlijkheid draagt.
=> AB#19385 Add beheerkaart map

beheerkaart.map
Belaste objecten met bgt_fysiekvoorkomen=erf zijn geen
deel van de publieke ruimte en worden uit de data gefilterd.
Dat deze businesslogica hier is ondergebracht is niet
wenselijk en aangekaart bij de datateams.
=> Remove objects with fysiekvoorkomen 'erf' from beheerkaart

wegenbestand.map
The wegenbestand contains data about so called zones zwaar verkeer en consists of roads within that zone, outside that zone and roads that needs a special waiver to be used. These three tables all fall within the main category wegenbestand and subcategory zones zwaar verkeer.
The existing datasets hoofdroutes, like routes and tunnels gevaarlijke stoffen are also placed on the wegenbestand but not under zones zwaar verkeer. They reside on the main level in that perspective.
The current `hoofdroutes.map` (where routes and tunnels gevaarlijke stoffen are also placed) will still remain for now. It will be de-allocated when dataportaal can switch fully to the `wegenbestand.map`.
=> [NEW] wegenbestand dataset

docker/000-default.conf
When I run
docker-compose up --build
curl -i -H "Origin: example.amsterdam.nl" http://localhost/maps/monumenten
I get an Access-Control-Allow-Origin header with example.amsterdam.nl in it.
=> Send Access-Control-Allow-Origin for amsterdam.nl and ARCGIS Online

parkeervakken.map
On request of source maintainer, changed the colorways of `parkeervakken regimes`
=> change color ways for parkeervakken regimes that are grey

.gitignore, docker/docker-entrypoint.sh, ondergrond.map, ondergrond/eisvoorzorgsmaatregelen_layer.inc, ondergrond/kabels_en_leidingen_layer.inc, ondergrond/objecten_layer.inc
In order to give clients more control over performance by loading stuff only when it is necessary. Also defined a reasonable max zoom denominator at 20000 based on experimentation with QGIS. 
The make_mapfile_config generation script has been commented out in the Dockerfile because it has been generating a lot of exceptions on valid mapfile syntax, preventing normal development. I think we should work towards removing this script since it is basically a very naive mapfile parser for which much better third party tools exist. The generated json file is also not used anywhere (it might be used by clients tho but it is not documented nor part of any spec)
=> Factor ondergrond map into separate layers

ondergrond.map, ondergrond/eisvoorzorgsmaatregelen_layer.inc, ondergrond/kabels_en_leidingen_layer.inc
implements 52384 partially (rioolleidingen remains todo)
- fixes historische_onderzoeken (broken for a long time :s)
- fixes eisvoorzorgsmaatregelen (layer extent was outside map extent)
- proper titles and names for kabelsleidingen, objecten and eisvoorzorgsmaatregelen
=> Add rioolknopen layer + various fixes in ondergrond map

docker-compose.yml, docker/docker-entrypoint.sh, infrarood.map, lufo.map
This is now hardcoded, which causes problems when testing new stuff that isnt available in prod yet. The OpenStack repo sets MAP_URL_REPLACE  to `http://localhost:80`
=> Inject the URL for the lufo layers from environment

adresseerbare_objecten.map, adresseerbare_objecten/ligplaatsen.inc, adresseerbare_objecten/standplaatsen.inc, adresseerbare_objecten/verblijfsobjecten.inc, symbols/symbollist.txt
to keep it a bit DRY (as far as mapfile syntax allows), the shared definitions have been included in their own directory.
=> Adresseerbare objecten kaartlagen

header.inc, private/header.inc
The diff between the two is now readable again.
XXX For some reason, the EXTENTs are different. They were both last changed with no reason in the commit message, so I left them as they were. Relevant commits:
12114a636af23384ab369bc1baa520d0b01ad8f0
046ee51dc1a8c6b01a634343887c57b44eca2569
3313801ca7b34c3572eb4b201cf45b1279e8730a
=> Equalize header.inc and private/header.inc

adresseerbare_objecten.map
GetLegendGraphic without rule parameter responds with an empty white image when a CLASS NAME is not defined. Contrary to what the docs says: https://mapserver.org/ogc/wms_server.html#parameters. We should be able to get the legend by omitting the rule parameter regardless of CLASS NAME. 
When name the classes the request does work so that is the solution for now.
=> Add named classes to adresserbare objecten to make GetLegendGraphic work

topografie_wm.map
In the containers on acc these are replaced with urls, so they can be resolved. `map` only works on local docker
=> Revert to url replace vars in topografie_wm.map

tools/make_indexjson.py
Diff:
--- old	2023-08-16 11:16:17.096685680 +0200
+++ new	2023-08-16 11:20:59.704663291 +0200
@@ -1,10 +1,10 @@
{
"BRK": {
-    "abstract": "BR",
+    "abstract": "BRK objecten met een geografische component",
"title": "BRK"
},
"BRK2": {
-    "abstract": "BRK-objecte",
+    "abstract": "BRK-objecten met een geografische component (BRK 2.0)",
"title": "BRK2"
},
"COVID19": {
@@ -12,131 +12,131 @@
"title": "COVID19"
},
"EIGENDOMMEN": {
-    "abstract": "Kadastral",
+    "abstract": "Kadastrale eigendommen, gecategoriseerd",
"title": "EIGENDOMMEN"
},
"ENERGIE": {
-    "abstract": "Ga",
+    "abstract": "Gas / elektra - verbruiks gegevens. BAG gecombineerd met Alliander open data",
"title": "energie"
},
"ERFPACHT": {
-    "abstract": "Kadastral",
+    "abstract": "Kadastrale erfpacht, …
=> Fix index.json

tools/make_indexjson.py
The name should just be the filename, not the name declared in the mapfile, because the former determines the URL.
=> Fix names in make_indexjson.py

gen_ziektenplagenexotengroen.py, ziektenplagenexotengroen.map
These were broken, but for some reason mapserver gives HTTP status 200 with an error message in the body, so I didn't notice when checking only the QGIS debug toolbar.
=> Fix caterpillar queries

monumenten.map
It selected too few fields to even execute its FILTER for "nopand". Select everything so we can satisfy `gml_include_items`, which restricts the fields served.
Fixes AB#93379.
=> Fix SQL bug in monumenten

tools/make_indexjson.py
These occur in our generated mapfiles. Diff of output on the mapfiles in the top-level dir:
26c26,29
<   "beschermdestadsdorpsgezichten": {},
---
>   "beschermdestadsdorpsgezichten": {
>     "abstract": "Kaart met gegevens over beschermde stads- en dorpsgezichten in de gemeente Amsterdam",
>     "title": "Beschermde stads- en dorpsgezichten"
>   },
47c50,53
<   "bomen": {},
---
>   "bomen": {
>     "abstract": "Dataset met actuele informatie over de bomen in beheer van gemeente Amsterdam",
>     "title": "Objecten openbare ruimte - bomen"
>   },
249c255,258
<   "overlastgebieden": {},
---
>   "overlastgebieden": {
>     "abstract": "Overlastgebieden",
>     "title": "Overlastgebieden"
>   },
338c347,350
<   "ziektenplagenexotengroen": {}
---
>   "ziektenplagenexotengroen": {
> …
=> Handle single quotes in make_indexjson.py

beschermdestadsdorpsgezichten.map, bomen.map, brk2.map, gen_beschermdestadsdorpsgezichten.py, gen_bomen.py, gen_ziektenplagenexotengroen.py, ziektenplagenexotengroen.map
I thought I disabled this in 16b122751e77b65e29df7ce0a08419da59d91cc8, following the recipe from #349, but that didn't work. Fix all maps that used the wrong recipe to prevent future copy-paste errors.
See also https://www.mapserver.org/development/rfc/ms-rfc-67.html.
=> Properly disable WFS for BRK2 and some other maps

docker/docker-entrypoint.sh
Now that topografie maps are restored, we also need these replacements again.
=> Restore url replacements for topografie.

docker/000-default.conf
There are some extra conditions in the Apache config for LOCAL development.
Those are depending on a LOCAL variable that has only been set in the docker-compose (so for local dev).
It turns out that these extra configs are blocking for the topgrafie (and lufo) maps.
This PR removes this config.
The config has been left in the code to be evaluated further in a later stage, because maybe it can be replaced with something less lethal that is helpful for local development.
=> Remove the extra conditions for apache

bag.map
This layer is unused. Its data is also available from adresseerbare_objecten.
=> Remove bag layer "verblijfsobjecten"

vastgoed.map
This reverts commit d59bc41505a8ff2a46282d043d475d2255246e67.
Doesn't solve the data.amsterdam.nl issue that we were trying to solve. Instead, Geosearch and DSO-API are inconsistent wrt. how to identify vastgoed objects.
=> Revert "In vastgoed.map, use verhuurbare_eenheid_nummer as id"

symbols/symbollist.txt
File was removed in #427, but left on the list.
=> Remove cirkel_correctie_punt from symbol list

header.inc, private/header.inc
This setting was inconsistent between header.inc and private/header.inc and out of date in both cases. It's bound to go out of date again, so no meaningful value entered. Not the empty string as I wasn't sure if that would work.
=> Set ows_contactperson to "N/A"

gebieden.map
aanpassingen aan gebieden mapfile
=> refdb aanpassingen en tabel naam wijzigingen

Dockerfile, epsg, projectiontest.map
Operating system updated to 22.04. MapServer minor version update picks up correct projection params from 'epsg' file.
=> Bump Ubuntu and Mapserver. 

meetbouten.map
Now two nested SELECTs instead of three. The left outer join is now an inner join, which doesn't matter because (1) each meetbout has some meting associated with it, and (2) if one didn't, it wouldn't match any of the classes defined for this layer.
Also removed the manual version control comment.
=> Simplify query for layer meetbout_zaksnelheid

.gitattributes
Without this, the scripts inside docker/ get checked out with CRLF endings on Windows. They then get copied into a Docker image with those endings and the script docker-entrypoint.sh borks:
/usr/bin/env: 'bash\r': No such file or directory
Be careful when editing these files on Windows.
=> CRLF/LF hack to ensure docker-compose works again on Windows

.github/workflows/test.yml
We previously ran into MapServer/MapServer#6478 when trying to upgrade our Ubuntu base image and added the file `epsg` as a hack to work around it in 20d7dc720b53366424f42f2769b31c9477b172a0. This adds a regression test for that upstream issue.
I have tested this with `COPY epsg /usr/share/proj` removed from `Dockerfile`, and that makes it fail.
=> Add BBOX test to CI/CD

jwtproxy/src/server.py
post request bodies are passed to upstream by jwtproxy
=> AB#117091 Fix postrequests

header.inc, nieuwbouwplannen.map
Added metadata properties to properly respond to a WFS GetFeature request. We're also removing as many MapServer specific sugar from the GML:
- the namespace for attributes is no longer "ms", but "amsterdam" and the url namespace is "https://amsterdam.nl/"
- the geometry column is no longer "msGeometry', but "amsterdam:geometry"
=> Include attributes in WFS GetFeature requests.

nieuwbouwplannen.map
If a database table contains MultiPolygons, but MapServer is set to serve polygons, it returns multiple geometries for each feature. Now that MapServer is set to serve MultiPolygons for this layer instead, it properly returns one geometry for each feature, i.e. a MultiPolygon.
=> Properly set geometry as MultiPolygon.

.mapfile_template.txt, nieuwbouwplannen.map
The `gml_geometry_type` meta tag in the MAP file must reflect the geometry type in the database.
=> Improve template MAP file

Dockerfile, Dockerfile.private, docker/docker-entrypoint.sh, jwtproxy/Dockerfile.prd, jwtproxy/supervisord.conf
add changes to run mapserver containers with non-privileged users. Tested with aks.
TODO: Might need follow up for docker-compose files for local dev deploys.
=> non-root for mapserver, mapserver-private & jwt-proxy

referentiekaarten/kbk10.map
=> Veerponten stippel met transparantie en iets meer rood 

jwtproxy/requirements.txt
The conflict is caused by:
The user requested yarl==1.8.1
aiohttp 3.10.11 depends on yarl<2.0 and >=1.12.0
=> bump yarl to 1.12.0

compose.yml, sld/kbk10_light.xml, sld/kbk10_zw.xml
Added the 'sld' directory to the container and also corrected the SLDs to style the map based on Top10NL data in black&white (zw) and light (light) variants.
=> Changes to enable multiple styles for reference map

referentiekaarten/bgt.map, referentiekaarten/kaartteksten.map, referentiekaarten/kbk10.map, referentiekaarten/kbk50.map, sld/bgt_light.xml, sld/bgt_zw.xml, sld/kbk10_light.xml, sld/kbk10_zw.xml, sld/kbk50_light.xml, sld/kbk50_zw.xml
- similar zoom levels show same information irrespective of projection
- widths of lines and dash arrays aligned between different visualisations
- SLDs adjusted for new layers because of migration to refDB
- filters adjusted to new column names in refDB
- SQL queries only select required columns for visualisation instead of selecting all columns
=> Align zoom levels and visualisation of BRT/BGT/BAG for topographic reference maps.

docker/000-default.conf
MapProxy sends millions of requests to the `/tiled/` endpoint of MapServer when it is making map tiles. It's just a waste of time and disk space if MapServer is logging all these requests.
=> Don't log requests from MapProxy.
